name: .NET Core Console App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore cli/src/Timesheet.csproj

    - name: Build
      run: dotnet build cli/src/Timesheet.csproj --configuration Release

#     - name: Test
#       run: dotnet test --no-build --verbosity normal
